POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "test",
  "password": "changeme"
}

###
POST http://localhost:3000/auth-v2/login
Content-Type: application/json

{
  "username": "test",
  "password": "changeme"
}

###

GET http://localhost:3000/auth/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOjUsImlhdCI6MTczNzA2ODU3MCwiZXhwIjoxNzM3MTU0OTcwfQ.bnhqYdoYMJKqU3EMbULQDRxCXhWreWtPljKOxRgVeRw

###

GET http://localhost:3000/auth-v2/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOjUsImlhdCI6MTczNzA2ODU3MCwiZXhwIjoxNzM3MTU0OTcwfQ.bnhqYdoYMJKqU3EMbULQDRxCXhWreWtPljKOxRgVeRw

###

POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "token": ""
}

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
  "first_name": "John",
  "last_name" : "Big",
  "email" : "testchangeme@gmail.com",
  "username": "test",
  "password" : "changeme"
}


###

POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "query { users { id first_name last_name age email username } }"
}

###

POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { createUser(createUserDto: { first_name: \"Jane\", last_name: \"Doe\", age: 25, email: \"jane.doe@example.com\", username: \"janedoe\", password: \"securepassword\" }) { id first_name last_name age email username } }"
}